### ISSUE TITLE
Updating the Database with a new release

### ISSUE THREAD

**Issue by Cliko** [Maerciez/TheMillionaireGame#15]
Hello,
Are there any plans to keep a database from one release to another?

Because I started to contribute a database, and I noticed that the notes field was not editable but would be in the next release.
It's just for information, but if it could be possible, that would be great!

Finally, when is the next release planned so that I can test your work? :)

I'll test FFF server soon and I'll tell you if I have troubles.

Thanks !

**Comment by Maerciez** [comment]
Hello Cliko,
I made some changes in the questions editor so that people will be able to add some notes and explanations to the questions.
This will be finished in the next release very soon.

**Comment by Maerciez** [comment]
Fixed in 1.0.344
