### ISSUE TITLE
Problem with question counter

### ISSUE THREAD

**Issue by Cliko** [Maerciez/TheMillionaireGame#16]
Hi!

I played a full game and just realized that level 4 questions never appear. I think you got it wrong with the levels because we should have a question of LVL4 when we are at the 14th level (500,000). Because when I validate it, we have the victory music of the 1,000,000.

Could you fix it quickly and do a new build? I'll need it quickly for a little night out with friends.

Thanks you!

**Comment by Cliko** [comment]
Ok, after read your code, I see that you are fix the problems. 
I redid a build and everything is working fine!

**Comment by Maerciez** [comment]
Yep, and i also released a new version today where this issue is fixed! ;)
