### ISSUE TITLE
Can't delete an existing question from the database in the Question Editor

### ISSUE THREAD

**Issue by JCEurovisionFan** [Maerciez/TheMillionaireGame#22]
Good evening.

I was trying to delete a FFF question from the database in the Question Editor, but once I clicked "Yes" to confirm the action, the question is still in the database and did NOT delete the entire question. Is there any way you can fix this issue?

**Comment by Maerciez** [comment]
This might be a problem with refreshing the table inside the application. Because the SQL query behind the program is working fine for me.
I will look into it. Thanks!

**Comment by Maerciez** [comment]
Fixed in 1.0.344
